services:
    app:
        build: .
        container_name: app
        ports:
            - 8085:8080
        environment:
            - DADATA_API_KEY=${DADATA_API_KEY}
            - DADATA_SECRET_KEY=${DADATA_SECRET_KEY}
            - TWO_GIS_API_KEY=${TWO_GIS_API_KEY}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - DATASOURCE_URL=${DATASOURCE_URL}
            - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
        depends_on:
            - postgres

    postgres:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
#            POSTGRES_PASSWORD_FILE: /run/secrets/db-password
        ports:
            - 5435:5432
        volumes:
            - pre-project-data:/pre-project-data

volumes:
    pre-project-data:
        name: "pre-project-data"
#secrets:
#    db-password:
#        file: db_password.txt