spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pre-project-2-3
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    servlet:
      load-on-startup: 1
  profiles:
    default: dev
    active: dev


roles:
  admin: ROLE_ADMIN
  user: ROLE_USER