spring:
  sql.init.mode: always
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    servlet:
      load-on-startup: 1
  profiles:
    default: dev
    active: ${SPRING_PROFILES_ACTIVE}


roles:
  admin: ROLE_ADMIN
  user: ROLE_USER