travel-time:
  dadataApiUrl: "http://host.docker.internal:8081/api/test/dadata"
  dadataApiKey: "someKey"
  dadataSecretKey: "someSecretKey"
  twoGisApiUrl: "http://host.docker.internal:8081/api/test/twogis/global?key="
  twoGisApiKey: "someKey"
  samplingStep: 20
  workingHours: 9
  amountOfTimeCheckedBeforeMinArrival: 30
  minArrivalHours: 9
  minArrivalMinutes: 0
  maxArrivalHours: 12
  maxArrivalMinutes: 0

logging:
  file:
    name: './logs/dev-pre-project-2-3.log'
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
      total-size-cap: 1GB